language: node_js
node_js:
- '8'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_script:
- npm install -g gulp-cli
script: gulp
before_install:
- openssl aes-256-cbc -K $encrypted_f709bde90b47_key -iv $encrypted_f709bde90b47_iv
  -in deploy_rsa.enc -out deploy_rsa -d
