language: node_js
node_js:
- '8'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_script:
- npm install -g gulp-cli
script: gulp && gulp test
addons:
  ssh_known_hosts: junkato.jp
before_deploy:
- test $TRAVIS_TEST_RESULT = 0
- openssl aes-256-cbc -K $encrypted_f709bde90b47_key -iv $encrypted_f709bde90b47_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet --exclude-from $TRAVIS_BUILD_DIR/rsync-excludes.txt $TRAVIS_BUILD_DIR/dist/ digitalmuseum@junkato.jp:/home/digitalmuseum/www/jk_new
