name: Publish
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
      - name: Set up Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version: 24
          cache: npm
      - name: Install dependencies
        run: npm ci --omit=optional
      - name: Build pages
        run: npm run build
      - name: Test built pages
        run: npm test
      - name: Add CNAME
        run: echo junkato.jp > ./dist/CNAME
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5.0.0
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5.0.0
