name: Publish assets
on:
  push:
    tags:
      - "v*"
jobs:
  publish-assets:
    name: publish-assets
    runs-on: ubuntu-latest
    steps:
      - name: Set env vars
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> ${GITHUB_ENV}
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Build package
        run: npm run build
      - name: Archive assets
        run: cd dist && zip -r ../stylesheets-${VERSION}.zip stylesheets/main.* fonts semantic/themes/default
      - name: Upload assets
        uses: softprops/action-gh-release@v1
        with:
          files: stylesheets-${{ env.VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
